name: P1-Search
on:
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-20.04
    env:
      OS: ubuntu-20.04
      PYTHON: '3.6'

    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: 'test search'
      run: |
        cd search
        python autograder.py | python ../check_grade.py > /tmp/output
        cat /tmp/output

    - name: 'check error'
      run: python check_error.py < /tmp/output
